sudo: required

language: python
python:
  - 3.6
  - 3.5
  - 3.4

install:
  - pip install -r requirements_dev.txt
  - pip install jupyter jinja2 coveralls cairosvg
  - pip install .
  - sudo apt-get install -y --no-install-recommends texlive-full pdf2svg

script:
  - "jupyter nbconvert --to html --execute Quickstart.ipynb && ls Quickstart.html"
  - pytest --cov=itikz

after_success: coveralls
